import type { EmittedFile } from "./validation";
import type { SiteSpec } from "./spec";

/**
 * The route sources for a generated site.
 *
 * The emitted files carry data, not markup: rendering lives in the shared
 * demo component system, so what the validator renders in-process and what
 * the deployed route renders in the browser are the same code path over
 * the same specification. That is what makes "the preview route renders"
 * a claim worth trusting before anything is pushed.
 */

export function routeSourceDir(spec: SiteSpec): string {
  return `platform/src/app${spec.route}`;
}

function literal(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function pageFile(spec: SiteSpec, path: string, importDepth: number): string {
  const page = spec.pages.find((item) => item.path === path);
  if (!page) throw new Error(`Cannot emit a page for "${path}" — it is not in the specification`);
  const dataImport = importDepth === 0 ? "./site.data" : "../site.data";
  return `import type { Metadata } from "next";
import { DemoSitePage } from "@/components/demos/DemoSite";
import { siteSpec } from "${dataImport}";

// Generated by the LYNQ Office website factory from founder-approved
// research. Every visible fact traces to the evidence ledger recorded on
// the Office project; edit the project evidence, not this file.

export const metadata: Metadata = {
  title: ${JSON.stringify(page.title)},
  description: ${JSON.stringify(page.description)},
  robots: { index: false, follow: false },
  openGraph: {
    title: ${JSON.stringify(page.title)},
    description: ${JSON.stringify(page.description)},
    type: "website",
  },
};

export default function ${componentName(path)}() {
  return <DemoSitePage spec={siteSpec} path={${JSON.stringify(path)}} />;
}
`;
}

function componentName(path: string): string {
  if (!path) return "DemoHomePage";
  return `Demo${path.split("-").map((part) => part.charAt(0).toUpperCase() + part.slice(1)).join("")}Page`;
}

function layoutFile(spec: SiteSpec): string {
  return `import type { Viewport } from "next";
import type { ReactNode } from "react";

// A prospect demo owns its own segment so it can set a mobile viewport and
// stay isolated from the LYNQ application chrome.

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: ${JSON.stringify(spec.design.palette.background)},
};

export default function DemoLayout({ children }: { children: ReactNode }) {
  return children;
}
`;
}

function dataFile(spec: SiteSpec): string {
  return `import type { SiteSpec } from "@/lib/office/website/spec";

// Generated site specification. It is typed against SiteSpec so a schema
// change breaks the build rather than silently degrading a live preview.

export const siteSpec: SiteSpec = ${literal(spec)};
`;
}

export function emitSiteFiles(spec: SiteSpec): EmittedFile[] {
  const dir = routeSourceDir(spec);
  const files: EmittedFile[] = [
    { path: `${dir}/site.data.ts`, content: dataFile(spec) },
    { path: `${dir}/layout.tsx`, content: layoutFile(spec) },
  ];
  for (const page of spec.pages) {
    files.push({
      path: page.path ? `${dir}/${page.path}/page.tsx` : `${dir}/page.tsx`,
      content: pageFile(spec, page.path, page.path ? 1 : 0),
    });
  }
  return files;
}
