// AUTO-GENERATED by scripts/build-media.mjs — do not edit by hand.
// Product+colourway -> real archive photography. See scripts/media-manifest.mjs
// for how each assignment was established (object-pixel colour analysis +
// visual confirmation against the live catalogue colour list).

export interface Frame {
  /** Framed real photography — the honest default for galleries. */
  photo: string;
  photoSmall: string;
  /** Alpha cut-out — for editorial composition over colour fields. */
  cut: string;
  cutSmall: string;
  /** width/height of the framed crop. */
  ratio: number;
  /** false when visual QA rejected the cut-out — use `photo`, never `cut`. */
  cutOk: boolean;
  frameId: string;
  /** True for a macro crop of another frame rather than a whole-bag view. */
  detail?: true;
  /** Set only on detail frames, which the generic alt would describe wrongly. */
  alt?: string;
}

function f(id: string, ratio: number, cutOk = true): Frame {
  return {
    // A rejected cut-out means the framed photo IS the hero image, so it
    // is built at 2600px. Every other frame is shown as a cut-out.
    photo: cutOk ? `/media/${id}-1600.webp` : `/media/${id}-2600.webp`,
    photoSmall: `/media/${id}-800.webp`,
    cut: `/media/${id}-cut-2600.webp`,
    cutSmall: `/media/${id}-cut-600.webp`,
    ratio,
    frameId: id,
    cutOk,
  };
}

/**
 * A macro DETAIL crop of a real frame (scripts/media-manifest.mjs,
 * DETAIL_CROPS). It is a rectangle out of the full-resolution original, so
 * there is no cut-out and no whole-bag silhouette: the crop IS the image,
 * and `-full` is its true size rather than a width it was enlarged to hit.
 */
function d(id: string, ratio: number, alt: string): Frame {
  return {
    photo: `/media/${id}-full.webp`,
    photoSmall: `/media/${id}-800.webp`,
    cut: `/media/${id}-full.webp`,
    cutSmall: `/media/${id}-800.webp`,
    ratio,
    frameId: id,
    cutOk: false,
    detail: true,
    alt,
  };
}

export const COLOUR_MEDIA: Record<string, Record<string, Frame[]>> = {
  "nova": {
    "Gold": [f("DSC05786", 1.8526), f("DSC05787", 1.0818), f("DSC05776", 1.7937), f("DSC05777", 1.2012)],
    "Black": [f("DSC05780", 1.9185), f("DSC05782", 1.0624), f("DSC05783", 1.1396)],
    "Champagne": [f("DSC05784", 1.9961), f("DSC05785", 1.2567)],
    "Silver": [f("DSC04868", 1.8699), f("DSC04869", 1.178)],
    "Rose Gold": [f("DSC04863", 1.8304), f("DSC04864", 1.1662), f("DSC04865", 1.1252)],
    "Silver & Gold": [f("DSC04866", 2.0776), f("DSC04867", 1.1642), f("DSC05778", 1.75), f("DSC05779", 1.3769)],
  },
  "vault": {
    "Brown": [f("DSC04876", 1.5326), f("DSC04877", 1.3735), f("DSC04878", 1.0221)],
    "Light Brown": [f("DSC05790", 1.4723), f("DSC05791", 1.2777)],
    "Olive Green": [f("DSC05792", 1.5284), f("DSC05793", 1.3389)],
  },
  "mini-luna": {
    "Red": [f("DSC05774", 1.1585), f("DSC05775", 1.097)],
    "Silver": [f("DSC04875", 1.2647)],
    "Gold": [f("DSC04874", 1.2445)],
    "Black": [f("DSC04872", 0.8909), f("DSC04873", 1.1564)],
    "Silver & Gold": [f("DSC04870", 1.3017), f("DSC04871", 1.2417)],
  },
  "loco": {
    "Brown": [f("DSC05765", 1.4652, false), f("DSC05770", 0.8032, false), d("loco-brown-detail", 1.3624, "Close detail of the Loco in Brown: crocheted stitch rows and the knotted top of the fringe")],
    "Burgundy": [f("DSC05772", 1.5101, false), f("DSC05773", 1.3371, false)],
  },
};

/** Photographed but NOT purchasable — editorial use only, never as a product option. */
export const EDITORIAL_ONLY: Record<string, Frame[]> = {
  "nova": [f("DSC04860", 1.2437), f("DSC04861", 1.1632), f("DSC04862", 1.5162)],
  "vault": [f("DSC05788", 1.5087), f("DSC05789", 1.3841)],
};

export const TEXTURES = {
  "fringe": { src: "/media/texture-fringe.webp", ratio: 1.2496 },
  "metallic": { src: "/media/texture-metallic.webp", ratio: 1.3848 },
  "chunky": { src: "/media/texture-chunky.webp", ratio: 1.803 },
  "gold": { src: "/media/texture-gold.webp", ratio: 2.4042 },
  "twotone": { src: "/media/texture-twotone.webp", ratio: 2.8669 },
} as const;
